// 汉字数据 - 300个常用汉字（适合幼儿和小学生）
const characters = [
  // 基础字（1-30）
  { id: 1, char: '人', pinyin: 'rén', words: ['人民', '人们', '人口'], image: '👤', strokes: 2, category: 'basic' },
  { id: 2, char: '口', pinyin: 'kǒu', words: ['人口', '门口', '口水'], image: '👄', strokes: 3, category: 'basic' },
  { id: 3, char: '手', pinyin: 'shǒu', words: ['手指', '手机', '手工'], image: '✋', strokes: 4, category: 'basic' },
  { id: 4, char: '足', pinyin: 'zú', words: ['足球', '手足', '满足'], image: '🦶', strokes: 7, category: 'basic' },
  { id: 5, char: '大', pinyin: 'dà', words: ['大人', '大小', '大家'], image: '📏', strokes: 3, category: 'basic' },
  { id: 6, char: '小', pinyin: 'xiǎo', words: ['小孩', '小事', '小心'], image: '🔬', strokes: 3, category: 'basic' },
  { id: 7, char: '上', pinyin: 'shàng', words: ['上面', '上山', '上学'], image: '⬆️', strokes: 3, category: 'basic' },
  { id: 8, char: '下', pinyin: 'xià', words: ['下面', '下雨', '下山'], image: '⬇️', strokes: 3, category: 'basic' },
  { id: 9, char: '左', pinyin: 'zuǒ', words: ['左边', '左右', '左手'], image: '⬅️', strokes: 5, category: 'basic' },
  { id: 10, char: '右', pinyin: 'yòu', words: ['右边', '右手', '左右'], image: '➡️', strokes: 5, category: 'basic' },
  { id: 11, char: '一', pinyin: 'yī', words: ['一个', '一起', '一天'], image: '1️⃣', strokes: 1, category: 'basic' },
  { id: 12, char: '二', pinyin: 'èr', words: ['二月', '第二', '二人'], image: '2️⃣', strokes: 2, category: 'basic' },
  { id: 13, char: '三', pinyin: 'sān', words: ['三个', '三月', '三人'], image: '3️⃣', strokes: 3, category: 'basic' },
  { id: 14, char: '四', pinyin: 'sì', words: ['四个', '四季', '四方'], image: '4️⃣', strokes: 5, category: 'basic' },
  { id: 15, char: '五', pinyin: 'wǔ', words: ['五个', '五月', '五天'], image: '5️⃣', strokes: 4, category: 'basic' },
  { id: 16, char: '六', pinyin: 'liù', words: ['六个', '六月', '六天'], image: '6️⃣', strokes: 4, category: 'basic' },
  { id: 17, char: '七', pinyin: 'qī', words: ['七个', '七月', '七天'], image: '7️⃣', strokes: 2, category: 'basic' },
  { id: 18, char: '八', pinyin: 'bā', words: ['八个', '八月', '八天'], image: '8️⃣', strokes: 2, category: 'basic' },
  { id: 19, char: '九', pinyin: 'jiǔ', words: ['九个', '九月', '九天'], image: '9️⃣', strokes: 2, category: 'basic' },
  { id: 20, char: '十', pinyin: 'shí', words: ['十个', '十日', '十分'], image: '🔟', strokes: 2, category: 'basic' },
  { id: 21, char: '个', pinyin: 'gè', words: ['一个', '个人', '个子'], image: '📍', strokes: 3, category: 'basic' },
  { id: 22, char: '半', pinyin: 'bàn', words: ['一半', '半边', '半年'], image: '½', strokes: 5, category: 'basic' },
  { id: 23, char: '双', pinyin: 'shuāng', words: ['双手', '双数', '成双'], image: '✌️', strokes: 4, category: 'basic' },
  { id: 24, char: '两', pinyin: 'liǎng', words: ['两个', '两边', '两人'], image: '2️⃣', strokes: 7, category: 'basic' },
  { id: 25, char: '中', pinyin: 'zhōng', words: ['中间', '中国', '中心'], image: '🎯', strokes: 4, category: 'basic' },
  { id: 26, char: '心', pinyin: 'xīn', words: ['心中', '开心', '心里'], image: '❤️', strokes: 4, category: 'basic' },
  { id: 27, char: '头', pinyin: 'tóu', words: ['头发', '头上', '开头'], image: '👤', strokes: 5, category: 'basic' },
  { id: 28, char: '身', pinyin: 'shēn', words: ['身体', '身边', '自身'], image: '🧍', strokes: 7, category: 'basic' },
  { id: 29, char: '耳', pinyin: 'ěr', words: ['耳朵', '耳目', '耳边'], image: '👂', strokes: 6, category: 'basic' },
  { id: 30, char: '目', pinyin: 'mù', words: ['目光', '目前', '耳目'], image: '👁️', strokes: 5, category: 'basic' },

  // 自然字（31-60）
  { id: 31, char: '山', pinyin: 'shān', words: ['大山', '山水', '上山'], image: '⛰️', strokes: 3, category: 'nature' },
  { id: 32, char: '水', pinyin: 'shuǐ', words: ['水果', '喝水', '河水'], image: '💧', strokes: 4, category: 'nature' },
  { id: 33, char: '火', pinyin: 'huǒ', words: ['火车', '火锅', '大火'], image: '🔥', strokes: 4, category: 'nature' },
  { id: 34, char: '木', pinyin: 'mù', words: ['树木', '木头', '森林'], image: '🌳', strokes: 4, category: 'nature' },
  { id: 35, char: '日', pinyin: 'rì', words: ['日出', '日记', '日子'], image: '☀️', strokes: 4, category: 'nature' },
  { id: 36, char: '月', pinyin: 'yuè', words: ['月亮', '月饼', '岁月'], image: '🌙', strokes: 4, category: 'nature' },
  { id: 37, char: '星', pinyin: 'xīng', words: ['星星', '明星', '星空'], image: '⭐', strokes: 9, category: 'nature' },
  { id: 38, char: '云', pinyin: 'yún', words: ['白云', '云朵', '乌云'], image: '☁️', strokes: 4, category: 'nature' },
  { id: 39, char: '天', pinyin: 'tiān', words: ['天空', '白天', '天气'], image: '🌌', strokes: 4, category: 'nature' },
  { id: 40, char: '地', pinyin: 'dì', words: ['地球', '土地', '地方'], image: '🌍', strokes: 6, category: 'nature' },
  { id: 41, char: '风', pinyin: 'fēng', words: ['大风', '风景', '风车'], image: '💨', strokes: 4, category: 'nature' },
  { id: 42, char: '雨', pinyin: 'yǔ', words: ['下雨', '雨水', '雨伞'], image: '🌧️', strokes: 8, category: 'nature' },
  { id: 43, char: '雪', pinyin: 'xuě', words: ['下雪', '雪人', '雪花'], image: '❄️', strokes: 11, category: 'nature' },
  { id: 44, char: '冰', pinyin: 'bīng', words: ['冰块', '冰雪', '溜冰'], image: '🧊', strokes: 6, category: 'nature' },
  { id: 45, char: '石', pinyin: 'shí', words: ['石头', '石子', '石桥'], image: '🪨', strokes: 5, category: 'nature' },
  { id: 46, char: '土', pinyin: 'tǔ', words: ['土地', '泥土', '土豆'], image: '🌱', strokes: 3, category: 'nature' },
  { id: 47, char: '沙', pinyin: 'shā', words: ['沙子', '沙滩', '沙坑'], image: '🏖️', strokes: 7, category: 'nature' },
  { id: 48, char: '海', pinyin: 'hǎi', words: ['大海', '海边', '海洋'], image: '🌊', strokes: 10, category: 'nature' },
  { id: 49, char: '河', pinyin: 'hé', words: ['小河', '河水', '河边'], image: '🏞️', strokes: 8, category: 'nature' },
  { id: 50, char: '湖', pinyin: 'hú', words: ['湖水', '湖边', '公园湖'], image: '🏞️', strokes: 12, category: 'nature' },
  { id: 51, char: '花', pinyin: 'huā', words: ['花朵', '鲜花', '花园'], image: '🌸', strokes: 7, category: 'nature' },
  { id: 52, char: '草', pinyin: 'cǎo', words: ['小草', '草地', '青草'], image: '🌿', strokes: 9, category: 'nature' },
  { id: 53, char: '树', pinyin: 'shù', words: ['大树', '树木', '树林'], image: '🌲', strokes: 9, category: 'nature' },
  { id: 54, char: '叶', pinyin: 'yè', words: ['叶子', '树叶', '绿叶'], image: '🍃', strokes: 5, category: 'nature' },
  { id: 55, char: '春', pinyin: 'chūn', words: ['春天', '春游', '春风'], image: '🌸', strokes: 9, category: 'nature' },
  { id: 56, char: '夏', pinyin: 'xià', words: ['夏天', '夏日', '立夏'], image: '☀️', strokes: 10, category: 'nature' },
  { id: 57, char: '秋', pinyin: 'qiū', words: ['秋天', '秋风', '中秋'], image: '🍂', strokes: 9, category: 'nature' },
  { id: 58, char: '冬', pinyin: 'dōng', words: ['冬天', '冬雪', '过冬'], image: '⛄', strokes: 5, category: 'nature' },
  { id: 59, char: '光', pinyin: 'guāng', words: ['光明', '阳光', '灯光'], image: '💡', strokes: 6, category: 'nature' },
  { id: 60, char: '阳', pinyin: 'yáng', words: ['太阳', '阳光', '阳台'], image: '🌞', strokes: 6, category: 'nature' },

  // 动物字（61-85）
  { id: 61, char: '狗', pinyin: 'gǒu', words: ['小狗', '狗熊', '热狗'], image: '🐕', strokes: 8, category: 'animal' },
  { id: 62, char: '猫', pinyin: 'māo', words: ['小猫', '猫咪', '熊猫'], image: '🐱', strokes: 11, category: 'animal' },
  { id: 63, char: '鸟', pinyin: 'niǎo', words: ['小鸟', '鸟儿', '鸟蛋'], image: '🐦', strokes: 5, category: 'animal' },
  { id: 64, char: '鱼', pinyin: 'yú', words: ['小鱼', '金鱼', '鱼缸'], image: '🐟', strokes: 8, category: 'animal' },
  { id: 65, char: '马', pinyin: 'mǎ', words: ['小马', '斑马', '马儿'], image: '🐴', strokes: 3, category: 'animal' },
  { id: 66, char: '牛', pinyin: 'niú', words: ['牛奶', '黄牛', '牛肉'], image: '🐂', strokes: 4, category: 'animal' },
  { id: 67, char: '羊', pinyin: 'yáng', words: ['小羊', '山羊', '羊毛'], image: '🐑', strokes: 6, category: 'animal' },
  { id: 68, char: '兔', pinyin: 'tù', words: ['兔子', '白兔', '兔耳'], image: '🐰', strokes: 8, category: 'animal' },
  { id: 69, char: '虫', pinyin: 'chóng', words: ['虫子', '昆虫', '毛虫'], image: '🐛', strokes: 6, category: 'animal' },
  { id: 70, char: '虎', pinyin: 'hǔ', words: ['老虎', '虎头', '虎年'], image: '🐯', strokes: 8, category: 'animal' },
  { id: 71, char: '鸡', pinyin: 'jī', words: ['小鸡', '公鸡', '鸡蛋'], image: '🐔', strokes: 7, category: 'animal' },
  { id: 72, char: '鸭', pinyin: 'yā', words: ['鸭子', '小鸭', '鸭蛋'], image: '🦆', strokes: 10, category: 'animal' },
  { id: 73, char: '鹅', pinyin: 'é', words: ['白鹅', '鹅毛', '天鹅'], image: '🦢', strokes: 12, category: 'animal' },
  { id: 74, char: '猪', pinyin: 'zhū', words: ['小猪', '猪肉', '猪头'], image: '🐷', strokes: 11, category: 'animal' },
  { id: 75, char: '象', pinyin: 'xiàng', words: ['大象', '象牙', '象鼻'], image: '🐘', strokes: 11, category: 'animal' },
  { id: 76, char: '狮', pinyin: 'shī', words: ['狮子', '狮王', '狮头'], image: '🦁', strokes: 9, category: 'animal' },
  { id: 77, char: '熊', pinyin: 'xióng', words: ['熊猫', '熊掌', '狗熊'], image: '🐻', strokes: 14, category: 'animal' },
  { id: 78, char: '蛙', pinyin: 'wā', words: ['青蛙', '蛙跳', '蛙泳'], image: '🐸', strokes: 12, category: 'animal' },
  { id: 79, char: '蝶', pinyin: 'dié', words: ['蝴蝶', '蝶舞', '彩蝶'], image: '🦋', strokes: 15, category: 'animal' },
  { id: 80, char: '蜂', pinyin: 'fēng', words: ['蜜蜂', '蜂巢', '蜂蜜'], image: '🐝', strokes: 13, category: 'animal' },
  { id: 81, char: '龟', pinyin: 'guī', words: ['乌龟', '海龟', '龟壳'], image: '🐢', strokes: 7, category: 'animal' },
  { id: 82, char: '蛇', pinyin: 'shé', words: ['蛇皮', '蛇头', '青蛇'], image: '🐍', strokes: 11, category: 'animal' },
  { id: 83, char: '鼠', pinyin: 'shǔ', words: ['老鼠', '松鼠', '鼠年'], image: '🐭', strokes: 13, category: 'animal' },
  { id: 84, char: '龙', pinyin: 'lóng', words: ['恐龙', '龙灯', '龙年'], image: '🐉', strokes: 5, category: 'animal' },
  { id: 85, char: '猴', pinyin: 'hóu', words: ['猴子', '猴山', '猴年'], image: '🐒', strokes: 12, category: 'animal' },

  // 食物字（86-115）
  { id: 86, char: '米', pinyin: 'mǐ', words: ['大米', '米饭', '米线'], image: '🍚', strokes: 6, category: 'food' },
  { id: 87, char: '饭', pinyin: 'fàn', words: ['米饭', '吃饭', '饭菜'], image: '🍲', strokes: 7, category: 'food' },
  { id: 88, char: '果', pinyin: 'guǒ', words: ['水果', '苹果', '果树'], image: '🍎', strokes: 8, category: 'food' },
  { id: 89, char: '菜', pinyin: 'cài', words: ['蔬菜', '买菜', '菜花'], image: '🥬', strokes: 11, category: 'food' },
  { id: 90, char: '肉', pinyin: 'ròu', words: ['牛肉', '猪肉', '肉丸'], image: '🥩', strokes: 6, category: 'food' },
  { id: 91, char: '蛋', pinyin: 'dàn', words: ['鸡蛋', '蛋糕', '蛋壳'], image: '🥚', strokes: 11, category: 'food' },
  { id: 92, char: '奶', pinyin: 'nǎi', words: ['牛奶', '奶奶', '奶茶'], image: '🥛', strokes: 5, category: 'food' },
  { id: 93, char: '茶', pinyin: 'chá', words: ['喝茶', '茶叶', '茶杯'], image: '🍵', strokes: 9, category: 'food' },
  { id: 94, char: '瓜', pinyin: 'guā', words: ['西瓜', '冬瓜', '瓜子'], image: '🍉', strokes: 5, category: 'food' },
  { id: 95, char: '豆', pinyin: 'dòu', words: ['豆子', '红豆', '豆浆'], image: '🫘', strokes: 7, category: 'food' },
  { id: 96, char: '面', pinyin: 'miàn', words: ['面条', '面包', '面粉'], image: '🍜', strokes: 9, category: 'food' },
  { id: 97, char: '包', pinyin: 'bāo', words: ['面包', '包子', '书包'], image: '🥟', strokes: 5, category: 'food' },
  { id: 98, char: '糖', pinyin: 'táng', words: ['糖果', '白糖', '糖水'], image: '🍬', strokes: 16, category: 'food' },
  { id: 99, char: '饼', pinyin: 'bǐng', words: ['饼干', '月饼', '大饼'], image: '🍪', strokes: 9, category: 'food' },
  { id: 100, char: '梨', pinyin: 'lí', words: ['梨子', '雪梨', '鸭梨'], image: '🍐', strokes: 11, category: 'food' },
  { id: 101, char: '桃', pinyin: 'táo', words: ['桃子', '桃树', '核桃'], image: '🍑', strokes: 10, category: 'food' },
  { id: 102, char: '杏', pinyin: 'xìng', words: ['杏子', '杏仁', '银杏'], image: '🍑', strokes: 7, category: 'food' },
  { id: 103, char: '橙', pinyin: 'chéng', words: ['橙子', '橙汁', '甜橙'], image: '🍊', strokes: 16, category: 'food' },
  { id: 104, char: '蕉', pinyin: 'jiāo', words: ['香蕉', '芭蕉', '蕉叶'], image: '🍌', strokes: 15, category: 'food' },
  { id: 105, char: '葡', pinyin: 'pú', words: ['葡萄', '葡萄干', '葡萄酒'], image: '🍇', strokes: 12, category: 'food' },
  { id: 106, char: '萄', pinyin: 'táo', words: ['葡萄', '葡萄干'], image: '🍇', strokes: 11, category: 'food' },
  { id: 107, char: '萝', pinyin: 'luó', words: ['萝卜', '菠萝', '胡萝卜'], image: '🥕', strokes: 11, category: 'food' },
  { id: 108, char: '卜', pinyin: 'bo', words: ['萝卜', '胡萝卜'], image: '🥕', strokes: 2, category: 'food' },
  { id: 109, char: '葱', pinyin: 'cōng', words: ['洋葱', '葱花', '大葱'], image: '🧅', strokes: 12, category: 'food' },
  { id: 110, char: '蒜', pinyin: 'suàn', words: ['大蒜', '蒜头', '蒜苗'], image: '🧄', strokes: 13, category: 'food' },
  { id: 111, char: '盐', pinyin: 'yán', words: ['食盐', '盐巴', '盐水'], image: '🧂', strokes: 10, category: 'food' },
  { id: 112, char: '油', pinyin: 'yóu', words: ['油条', '汽油', '油灯'], image: '🛢️', strokes: 8, category: 'food' },
  { id: 113, char: '酱', pinyin: 'jiàng', words: ['酱油', '果酱', '酱料'], image: '🫙', strokes: 13, category: 'food' },
  { id: 114, char: '味', pinyin: 'wèi', words: ['味道', '口味', '香味'], image: '👅', strokes: 8, category: 'food' },
  { id: 115, char: '饿', pinyin: 'è', words: ['肚子饿', '饥饿', '饿着'], image: '😋', strokes: 10, category: 'food' },

  // 家庭字（116-135）
  { id: 116, char: '爸', pinyin: 'bà', words: ['爸爸', '老爸', '爸妈'], image: '👨', strokes: 8, category: 'family' },
  { id: 117, char: '妈', pinyin: 'mā', words: ['妈妈', '奶奶', '大妈'], image: '👩', strokes: 6, category: 'family' },
  { id: 118, char: '爷', pinyin: 'yé', words: ['爷爷', '大爷', '老爷'], image: '👴', strokes: 6, category: 'family' },
  { id: 119, char: '奶', pinyin: 'nǎi', words: ['奶奶', '牛奶', '奶粉'], image: '👵', strokes: 5, category: 'family' },
  { id: 120, char: '哥', pinyin: 'gē', words: ['哥哥', '大哥', '哥们'], image: '👦', strokes: 10, category: 'family' },
  { id: 121, char: '弟', pinyin: 'dì', words: ['弟弟', '兄弟', '弟子'], image: '👦', strokes: 7, category: 'family' },
  { id: 122, char: '姐', pinyin: 'jiě', words: ['姐姐', '姐妹', '大姐'], image: '👧', strokes: 8, category: 'family' },
  { id: 123, char: '妹', pinyin: 'mèi', words: ['妹妹', '姐妹', '姐妹'], image: '👧', strokes: 8, category: 'family' },
  { id: 124, char: '家', pinyin: 'jiā', words: ['家人', '回家', '大家'], image: '🏠', strokes: 10, category: 'family' },
  { id: 125, char: '亲', pinyin: 'qīn', words: ['亲人', '亲爱', '父亲'], image: '👨‍👩‍👧', strokes: 9, category: 'family' },
  { id: 126, char: '父', pinyin: 'fù', words: ['父亲', '父母', '父子'], image: '👨', strokes: 4, category: 'family' },
  { id: 127, char: '母', pinyin: 'mǔ', words: ['母亲', '父母', '母子'], image: '👩', strokes: 5, category: 'family' },
  { id: 128, char: '子', pinyin: 'zǐ', words: ['儿子', '子女', '孩子'], image: '👶', strokes: 3, category: 'family' },
  { id: 129, char: '女', pinyin: 'nǚ', words: ['女儿', '女生', '女人'], image: '👧', strokes: 3, category: 'family' },
  { id: 130, char: '男', pinyin: 'nán', words: ['男生', '男人', '男孩'], image: '👦', strokes: 7, category: 'family' },
  { id: 131, char: '孩', pinyin: 'hái', words: ['孩子', '小孩', '男孩'], image: '👶', strokes: 9, category: 'family' },
  { id: 132, char: '孙', pinyin: 'sūn', words: ['孙子', '孙女', '子孙'], image: '👦', strokes: 6, category: 'family' },
  { id: 133, char: '叔', pinyin: 'shū', words: ['叔叔', '大叔', '叔父'], image: '👨', strokes: 8, category: 'family' },
  { id: 134, char: '姨', pinyin: 'yí', words: ['阿姨', '姨妈', '姨父'], image: '👩', strokes: 9, category: 'family' },
  { id: 135, char: '宝', pinyin: 'bǎo', words: ['宝宝', '宝贝', '宝物'], image: '👶', strokes: 8, category: 'family' },

  // 动作字（136-165）
  { id: 136, char: '吃', pinyin: 'chī', words: ['吃饭', '好吃', '吃东西'], image: '😋', strokes: 6, category: 'action' },
  { id: 137, char: '喝', pinyin: 'hē', words: ['喝水', '喝茶', '喝酒'], image: '🥤', strokes: 12, category: 'action' },
  { id: 138, char: '看', pinyin: 'kàn', words: ['看书', '看见', '好看'], image: '👀', strokes: 9, category: 'action' },
  { id: 139, char: '听', pinyin: 'tīng', words: ['听歌', '好听', '听见'], image: '👂', strokes: 7, category: 'action' },
  { id: 140, char: '说', pinyin: 'shuō', words: ['说话', '说话', '小说'], image: '🗣️', strokes: 9, category: 'action' },
  { id: 141, char: '走', pinyin: 'zǒu', words: ['走路', '行走', '走开'], image: '🚶', strokes: 7, category: 'action' },
  { id: 142, char: '跑', pinyin: 'pǎo', words: ['跑步', '跑步', '奔跑'], image: '🏃', strokes: 11, category: 'action' },
  { id: 143, char: '跳', pinyin: 'tiào', words: ['跳舞', '跳绳', '跳远'], image: '🤸', strokes: 11, category: 'action' },
  { id: 144, char: '坐', pinyin: 'zuò', words: ['坐下', '坐车', '请坐'], image: '🪑', strokes: 7, category: 'action' },
  { id: 145, char: '站', pinyin: 'zhàn', words: ['站立', '车站', '站着'], image: '🧍', strokes: 10, category: 'action' },
  { id: 146, char: '睡', pinyin: 'shuì', words: ['睡觉', '睡着', '午睡'], image: '😴', strokes: 13, category: 'action' },
  { id: 147, char: '醒', pinyin: 'xǐng', words: ['醒来', '清醒', '睡醒'], image: '😊', strokes: 16, category: 'action' },
  { id: 148, char: '笑', pinyin: 'xiào', words: ['笑声', '微笑', '笑话'], image: '😄', strokes: 10, category: 'action' },
  { id: 149, char: '哭', pinyin: 'kū', words: ['哭泣', '哭声', '大哭'], image: '😢', strokes: 10, category: 'action' },
  { id: 150, char: '唱', pinyin: 'chàng', words: ['唱歌', '唱戏', '合唱'], image: '🎤', strokes: 11, category: 'action' },
  { id: 151, char: '画', pinyin: 'huà', words: ['画画', '图画', '画家'], image: '🎨', strokes: 8, category: 'action' },
  { id: 152, char: '写', pinyin: 'xiě', words: ['写字', '书写', '写作'], image: '✍️', strokes: 5, category: 'action' },
  { id: 153, char: '读', pinyin: 'dú', words: ['读书', '阅读', '朗读'], image: '📖', strokes: 10, category: 'action' },
  { id: 154, char: '学', pinyin: 'xué', words: ['学习', '上学', '学校'], image: '📚', strokes: 8, category: 'action' },
  { id: 155, char: '教', pinyin: 'jiāo', words: ['教师', '教书', '教导'], image: '👨‍🏫', strokes: 11, category: 'action' },
  { id: 156, char: '玩', pinyin: 'wán', words: ['玩耍', '玩具', '好玩'], image: '🎮', strokes: 8, category: 'action' },
  { id: 157, char: '游', pinyin: 'yóu', words: ['游泳', '游戏', '旅游'], image: '🏊', strokes: 12, category: 'action' },
  { id: 158, char: '飞', pinyin: 'fēi', words: ['飞机', '飞行', '飞鸟'], image: '✈️', strokes: 3, category: 'action' },
  { id: 159, char: '开', pinyin: 'kāi', words: ['开门', '开心', '开始'], image: '🚪', strokes: 4, category: 'action' },
  { id: 160, char: '关', pinyin: 'guān', words: ['关门', '开关', '关灯'], image: '🚫', strokes: 6, category: 'action' },
  { id: 161, char: '洗', pinyin: 'xǐ', words: ['洗手', '洗脸', '洗衣服'], image: '🧼', strokes: 9, category: 'action' },
  { id: 162, char: '扫', pinyin: 'sǎo', words: ['扫地', '打扫', '扫除'], image: '🧹', strokes: 6, category: 'action' },
  { id: 163, char: '帮', pinyin: 'bāng', words: ['帮忙', '帮助', '帮手'], image: '🤝', strokes: 9, category: 'action' },
  { id: 164, char: '送', pinyin: 'sòng', words: ['送给', '送人', '送礼'], image: '🎁', strokes: 9, category: 'action' },
  { id: 165, char: '找', pinyin: 'zhǎo', words: ['找到', '寻找', '找人'], image: '🔍', strokes: 7, category: 'action' },

  // 形容词（166-190）
  { id: 166, char: '好', pinyin: 'hǎo', words: ['好人', '好看', '友好'], image: '👍', strokes: 6, category: 'adj' },
  { id: 167, char: '美', pinyin: 'měi', words: ['美丽', '美好', '美术'], image: '🌸', strokes: 9, category: 'adj' },
  { id: 168, char: '丑', pinyin: 'chǒu', words: ['丑陋', '丑小鸭'], image: '🦆', strokes: 4, category: 'adj' },
  { id: 169, char: '多', pinyin: 'duō', words: ['多少', '很多', '多多'], image: '➕', strokes: 6, category: 'adj' },
  { id: 170, char: '少', pinyin: 'shǎo', words: ['多少', '少女', '少数'], image: '➖', strokes: 4, category: 'adj' },
  { id: 171, char: '高', pinyin: 'gāo', words: ['高山', '高兴', '高矮'], image: '📏', strokes: 10, category: 'adj' },
  { id: 172, char: '矮', pinyin: 'ǎi', words: ['高矮', '矮小'], image: '🤏', strokes: 13, category: 'adj' },
  { id: 173, char: '长', pinyin: 'cháng', words: ['长城', '长长', '长度'], image: '📏', strokes: 4, category: 'adj' },
  { id: 174, char: '短', pinyin: 'duǎn', words: ['长短', '短暂'], image: '✂️', strokes: 12, category: 'adj' },
  { id: 175, char: '快', pinyin: 'kuài', words: ['快乐', '快跑', '快点'], image: '⚡', strokes: 7, category: 'adj' },
  { id: 176, char: '慢', pinyin: 'màn', words: ['慢走', '慢慢', '快慢'], image: '🐢', strokes: 14, category: 'adj' },
  { id: 177, char: '新', pinyin: 'xīn', words: ['新年', '新衣', '新旧'], image: '✨', strokes: 13, category: 'adj' },
  { id: 178, char: '旧', pinyin: 'jiù', words: ['旧书', '破旧', '新旧'], image: '📚', strokes: 5, category: 'adj' },
  { id: 179, char: '老', pinyin: 'lǎo', words: ['老人', '老师', '老少'], image: '👴', strokes: 6, category: 'adj' },
  { id: 180, char: '少', pinyin: 'shào', words: ['少年', '少女', '老少'], image: '👦', strokes: 4, category: 'adj' },
  { id: 181, char: '大', pinyin: 'dà', words: ['大人', '大小', '大家'], image: '🐘', strokes: 3, category: 'adj' },
  { id: 182, char: '小', pinyin: 'xiǎo', words: ['小孩', '小事', '小河'], image: '🐭', strokes: 3, category: 'adj' },
  { id: 183, char: '真', pinyin: 'zhēn', words: ['真的', '真实', '认真'], image: '✅', strokes: 10, category: 'adj' },
  { id: 184, char: '假', pinyin: 'jiǎ', words: ['假的', '假装', '真假'], image: '❌', strokes: 11, category: 'adj' },
  { id: 185, char: '香', pinyin: 'xiāng', words: ['花香', '香水', '香甜'], image: '🌸', strokes: 9, category: 'adj' },
  { id: 186, char: '臭', pinyin: 'chòu', words: ['臭味', '臭虫', '香臭'], image: '💨', strokes: 10, category: 'adj' },
  { id: 187, char: '甜', pinyin: 'tián', words: ['甜蜜', '甜味', '香甜'], image: '🍬', strokes: 11, category: 'adj' },
  { id: 188, char: '苦', pinyin: 'kǔ', words: ['苦味', '吃苦', '甘苦'], image: '☕', strokes: 8, category: 'adj' },
  { id: 189, char: '热', pinyin: 'rè', words: ['热水', '热闹', '热天'], image: '🔥', strokes: 10, category: 'adj' },
  { id: 190, char: '冷', pinyin: 'lěng', words: ['冷水', '寒冷', '冷热'], image: '❄️', strokes: 7, category: 'adj' },

  // 颜色字（191-205）
  { id: 191, char: '红', pinyin: 'hóng', words: ['红色', '红火', '苹果'], image: '🔴', strokes: 6, category: 'color' },
  { id: 192, char: '黄', pinyin: 'huáng', words: ['黄色', '金黄', '黄瓜'], image: '🟡', strokes: 11, category: 'color' },
  { id: 193, char: '蓝', pinyin: 'lán', words: ['蓝色', '蓝天', '蓝天'], image: '🔵', strokes: 13, category: 'color' },
  { id: 194, char: '绿', pinyin: 'lǜ', words: ['绿色', '绿叶', '草地'], image: '🟢', strokes: 11, category: 'color' },
  { id: 195, char: '白', pinyin: 'bái', words: ['白色', '白天', '白云'], image: '⚪', strokes: 5, category: 'color' },
  { id: 196, char: '黑', pinyin: 'hēi', words: ['黑色', '黑夜', '黑板'], image: '⚫', strokes: 12, category: 'color' },
  { id: 197, char: '紫', pinyin: 'zǐ', words: ['紫色', '紫菜', '紫花'], image: '🟣', strokes: 12, category: 'color' },
  { id: 198, char: '橙', pinyin: 'chéng', words: ['橙色', '橙子', '橙黄'], image: '🟠', strokes: 16, category: 'color' },
  { id: 199, char: '粉', pinyin: 'fěn', words: ['粉色', '粉红', '花粉'], image: '💗', strokes: 10, category: 'color' },
  { id: 200, char: '灰', pinyin: 'huī', words: ['灰色', '灰尘', '灰烬'], image: '🩶', strokes: 6, category: 'color' },
  { id: 201, char: '金', pinyin: 'jīn', words: ['金色', '金子', '金黄'], image: '🥇', strokes: 8, category: 'color' },
  { id: 202, char: '银', pinyin: 'yín', words: ['银色', '银子', '银白'], image: '🥈', strokes: 11, category: 'color' },
  { id: 203, char: '彩', pinyin: 'cǎi', words: ['彩色', '彩虹', '多彩'], image: '🌈', strokes: 11, category: 'color' },
  { id: 204, char: '色', pinyin: 'sè', words: ['颜色', '彩色', '红色'], image: '🎨', strokes: 6, category: 'color' },
  { id: 205, char: '亮', pinyin: 'liàng', words: ['明亮', '亮光', '月亮'], image: '✨', strokes: 9, category: 'color' },

  // 物品字（206-245）
  { id: 206, char: '书', pinyin: 'shū', words: ['书本', '看书', '读书'], image: '📚', strokes: 4, category: 'object' },
  { id: 207, char: '本', pinyin: 'běn', words: ['本子', '书本', '本人'], image: '📓', strokes: 5, category: 'object' },
  { id: 208, char: '笔', pinyin: 'bǐ', words: ['铅笔', '毛笔', '笔头'], image: '✏️', strokes: 10, category: 'object' },
  { id: 209, char: '纸', pinyin: 'zhǐ', words: ['纸张', '白纸', '纸巾'], image: '📄', strokes: 7, category: 'object' },
  { id: 210, char: '尺', pinyin: 'chǐ', words: ['尺子', '直尺', '卷尺'], image: '📏', strokes: 4, category: 'object' },
  { id: 211, char: '刀', pinyin: 'dāo', words: ['小刀', '刀子', '菜刀'], image: '🔪', strokes: 2, category: 'object' },
  { id: 212, char: '剪', pinyin: 'jiǎn', words: ['剪刀', '剪开', '剪纸'], image: '✂️', strokes: 11, category: 'object' },
  { id: 213, char: '胶', pinyin: 'jiāo', words: ['胶水', '胶带', '胶棒'], image: '🧴', strokes: 10, category: 'object' },
  { id: 214, char: '球', pinyin: 'qiú', words: ['皮球', '足球', '篮球'], image: '⚽', strokes: 11, category: 'object' },
  { id: 215, char: '车', pinyin: 'chē', words: ['汽车', '火车', '车子'], image: '🚗', strokes: 4, category: 'object' },
  { id: 216, char: '船', pinyin: 'chuán', words: ['小船', '轮船', '船头'], image: '🚢', strokes: 11, category: 'object' },
  { id: 217, char: '门', pinyin: 'mén', words: ['门口', '开门', '大门'], image: '🚪', strokes: 3, category: 'object' },
  { id: 218, char: '窗', pinyin: 'chuāng', words: ['窗户', '门窗', '窗口'], image: '🪟', strokes: 12, category: 'object' },
  { id: 219, char: '灯', pinyin: 'dēng', words: ['电灯', '台灯', '灯光'], image: '💡', strokes: 6, category: 'object' },
  { id: 220, char: '衣', pinyin: 'yī', words: ['衣服', '穿衣', '大衣'], image: '👕', strokes: 6, category: 'object' },
  { id: 221, char: '鞋', pinyin: 'xié', words: ['鞋子', '皮鞋', '穿鞋'], image: '👟', strokes: 15, category: 'object' },
  { id: 222, char: '帽', pinyin: 'mào', words: ['帽子', '草帽', '戴帽'], image: '🧢', strokes: 12, category: 'object' },
  { id: 223, char: '袜', pinyin: 'wà', words: ['袜子', '穿袜', '丝袜'], image: '🧦', strokes: 10, category: 'object' },
  { id: 224, char: '桌', pinyin: 'zhuō', words: ['桌子', '书桌', '餐桌'], image: '🪑', strokes: 10, category: 'object' },
  { id: 225, char: '椅', pinyin: 'yǐ', words: ['椅子', '座椅', '坐椅'], image: '🪑', strokes: 12, category: 'object' },
  { id: 226, char: '床', pinyin: 'chuáng', words: ['床铺', '床单', '小床'], image: '🛏️', strokes: 7, category: 'object' },
  { id: 227, char: '被', pinyin: 'bèi', words: ['被子', '棉被', '被单'], image: '🛌', strokes: 10, category: 'object' },
  { id: 228, char: '枕', pinyin: 'zhěn', words: ['枕头', '枕巾', '枕套'], image: '🛌', strokes: 8, category: 'object' },
  { id: 229, char: '钟', pinyin: 'zhōng', words: ['时钟', '钟表', '闹钟'], image: '⏰', strokes: 9, category: 'object' },
  { id: 230, char: '表', pinyin: 'biǎo', words: ['手表', '钟表', '表面'], image: '⌚', strokes: 8, category: 'object' },
  { id: 231, char: '镜', pinyin: 'jìng', words: ['镜子', '眼镜', '放大镜'], image: '🪞', strokes: 16, category: 'object' },
  { id: 232, char: '扇', pinyin: 'shàn', words: ['扇子', '电扇', '风扇'], image: '🪭', strokes: 10, category: 'object' },
  { id: 233, char: '伞', pinyin: 'sǎn', words: ['雨伞', '打伞', '伞把'], image: '☂️', strokes: 6, category: 'object' },
  { id: 234, char: '包', pinyin: 'bāo', words: ['书包', '背包', '包子'], image: '🎒', strokes: 5, category: 'object' },
  { id: 235, char: '箱', pinyin: 'xiāng', words: ['箱子', '冰箱', '木箱'], image: '📦', strokes: 15, category: 'object' },
  { id: 236, char: '桶', pinyin: 'tǒng', words: ['水桶', '铁桶', '木桶'], image: '🪣', strokes: 11, category: 'object' },
  { id: 237, char: '盆', pinyin: 'pén', words: ['脸盆', '花盆', '水盆'], image: '🪴', strokes: 9, category: 'object' },
  { id: 238, char: '杯', pinyin: 'bēi', words: ['杯子', '水杯', '茶杯'], image: '🥤', strokes: 8, category: 'object' },
  { id: 239, char: '碗', pinyin: 'wǎn', words: ['饭碗', '碗筷', '大碗'], image: '🥣', strokes: 13, category: 'object' },
  { id: 240, char: '筷', pinyin: 'kuài', words: ['筷子', '碗筷', '竹筷'], image: '🥢', strokes: 13, category: 'object' },
  { id: 241, char: '盘', pinyin: 'pán', words: ['盘子', '菜盘', '果盘'], image: '🍽️', strokes: 11, category: 'object' },
  { id: 242, char: '壶', pinyin: 'hú', words: ['水壶', '茶壶', '酒壶'], image: '🫖', strokes: 10, category: 'object' },
  { id: 243, char: '刷', pinyin: 'shuā', words: ['牙刷', '刷子', '粉刷'], image: '🪥', strokes: 8, category: 'object' },
  { id: 244, char: '巾', pinyin: 'jīn', words: ['毛巾', '围巾', '纸巾'], image: '🧣', strokes: 3, category: 'object' },
  { id: 245, char: '镜', pinyin: 'jìng', words: ['眼镜', '镜子', '放大镜'], image: '👓', strokes: 16, category: 'object' },

  // 身体部位（246-265）
  { id: 246, char: '头', pinyin: 'tóu', words: ['头发', '头上', '点头'], image: '👤', strokes: 5, category: 'body' },
  { id: 247, char: '脸', pinyin: 'liǎn', words: ['脸上', '笑脸', '脸蛋'], image: '😊', strokes: 11, category: 'body' },
  { id: 248, char: '眼', pinyin: 'yǎn', words: ['眼睛', '眼里', '眼泪'], image: '👀', strokes: 11, category: 'body' },
  { id: 249, char: '眉', pinyin: 'méi', words: ['眉毛', '眉目', '眉头'], image: '👀', strokes: 9, category: 'body' },
  { id: 250, char: '鼻', pinyin: 'bí', words: ['鼻子', '鼻孔', '鼻涕'], image: '👃', strokes: 14, category: 'body' },
  { id: 251, char: '嘴', pinyin: 'zuǐ', words: ['嘴巴', '嘴角', '张嘴'], image: '👄', strokes: 16, category: 'body' },
  { id: 252, char: '牙', pinyin: 'yá', words: ['牙齿', '门牙', '牙医'], image: '🦷', strokes: 4, category: 'body' },
  { id: 253, char: '舌', pinyin: 'shé', words: ['舌头', '舌尖', '舌根'], image: '👅', strokes: 6, category: 'body' },
  { id: 254, char: '颈', pinyin: 'jǐng', words: ['脖子', '颈项', '颈椎'], image: '🧣', strokes: 11, category: 'body' },
  { id: 255, char: '臂', pinyin: 'bì', words: ['手臂', '胳臂', '双臂'], image: '💪', strokes: 17, category: 'body' },
  { id: 256, char: '掌', pinyin: 'zhǎng', words: ['手掌', '鼓掌', '掌心'], image: '✋', strokes: 12, category: 'body' },
  { id: 257, char: '指', pinyin: 'zhǐ', words: ['手指', '指甲', '指向'], image: '👆', strokes: 9, category: 'body' },
  { id: 258, char: '胸', pinyin: 'xiōng', words: ['胸口', '心胸', '胸膛'], image: '👕', strokes: 10, category: 'body' },
  { id: 259, char: '背', pinyin: 'bèi', words: ['背后', '背包', '后背'], image: '🔙', strokes: 9, category: 'body' },
  { id: 260, char: '腰', pinyin: 'yāo', words: ['弯腰', '腰子', '后腰'], image: '🧘', strokes: 13, category: 'body' },
  { id: 261, char: '腿', pinyin: 'tuǐ', words: ['大腿', '小腿', '双腿'], image: '🦵', strokes: 13, category: 'body' },
  { id: 262, char: '膝', pinyin: 'xī', words: ['膝盖', '膝头', '屈膝'], image: '🦵', strokes: 15, category: 'body' },
  { id: 263, char: '脚', pinyin: 'jiǎo', words: ['脚丫', '脚步', '双脚'], image: '🦶', strokes: 11, category: 'body' },
  { id: 264, char: '趾', pinyin: 'zhǐ', words: ['脚趾', '趾甲', '足趾'], image: '🦶', strokes: 10, category: 'body' },
  { id: 265, char: '肤', pinyin: 'fū', words: ['皮肤', '肤色', '白肤'], image: '🖐️', strokes: 8, category: 'body' },

  // 学校用品（266-285）
  { id: 266, char: '校', pinyin: 'xiào', words: ['学校', '校园', '校长'], image: '🏫', strokes: 10, category: 'school' },
  { id: 267, char: '班', pinyin: 'bān', words: ['班级', '班长', '上班'], image: '👨‍🎓', strokes: 10, category: 'school' },
  { id: 268, char: '课', pinyin: 'kè', words: ['上课', '课本', '下课'], image: '📖', strokes: 10, category: 'school' },
  { id: 269, char: '师', pinyin: 'shī', words: ['老师', '教师', '师父'], image: '👨‍🏫', strokes: 6, category: 'school' },
  { id: 270, char: '生', pinyin: 'shēng', words: ['学生', '生活', '生日'], image: '👨‍🎓', strokes: 5, category: 'school' },
  { id: 271, char: '字', pinyin: 'zì', words: ['写字', '汉字', '字母'], image: '✍️', strokes: 6, category: 'school' },
  { id: 272, char: '词', pinyin: 'cí', words: ['词语', '单词', '词汇'], image: '📝', strokes: 7, category: 'school' },
  { id: 273, char: '句', pinyin: 'jù', words: ['句子', '造句', '句号'], image: '📝', strokes: 5, category: 'school' },
  { id: 274, char: '题', pinyin: 'tí', words: ['题目', '问题', '做题'], image: '❓', strokes: 12, category: 'school' },
  { id: 275, char: '答', pinyin: 'dá', words: ['回答', '答案', '问答'], image: '✅', strokes: 12, category: 'school' },
  { id: 276, char: '考', pinyin: 'kǎo', words: ['考试', '考查', '考场'], image: '📝', strokes: 6, category: 'school' },
  { id: 277, char: '卷', pinyin: 'juàn', words: ['试卷', '卷子', '答卷'], image: '📄', strokes: 8, category: 'school' },
  { id: 278, char: '作', pinyin: 'zuò', words: ['作业', '作文', '工作'], image: '📝', strokes: 7, category: 'school' },
  { id: 279, char: '业', pinyin: 'yè', words: ['作业', '事业', '学业'], image: '📚', strokes: 5, category: 'school' },
  { id: 280, char: '习', pinyin: 'xí', words: ['学习', '练习', '自习'], image: '📖', strokes: 3, category: 'school' },
  { id: 281, char: '练', pinyin: 'liàn', words: ['练习', '训练', '熟练'], image: '✍️', strokes: 8, category: 'school' },
  { id: 282, char: '画', pinyin: 'huà', words: ['画画', '图画', '画本'], image: '🎨', strokes: 8, category: 'school' },
  { id: 283, char: '图', pinyin: 'tú', words: ['图画', '地图', '图书'], image: '🗺️', strokes: 8, category: 'school' },
  { id: 284, char: '馆', pinyin: 'guǎn', words: ['图书馆', '饭馆', '博物馆'], image: '🏛️', strokes: 11, category: 'school' },
  { id: 285, char: '操', pinyin: 'cāo', words: ['操场', '体操', '做操'], image: '🏃', strokes: 16, category: 'school' },

  // 交通出行（286-300）
  { id: 286, char: '车', pinyin: 'chē', words: ['汽车', '火车', '自行车'], image: '🚗', strokes: 4, category: 'traffic' },
  { id: 287, char: '路', pinyin: 'lù', words: ['马路', '路上', '道路'], image: '🛣️', strokes: 13, category: 'traffic' },
  { id: 288, char: '道', pinyin: 'dào', words: ['道路', '知道', '街道'], image: '🛣️', strokes: 12, category: 'traffic' },
  { id: 289, char: '街', pinyin: 'jiē', words: ['街道', '大街', '逛街'], image: '🏙️', strokes: 12, category: 'traffic' },
  { id: 290, char: '桥', pinyin: 'qiáo', words: ['大桥', '过桥', '桥洞'], image: '🌉', strokes: 10, category: 'traffic' },
  { id: 291, char: '站', pinyin: 'zhàn', words: ['车站', '站牌', '加油站'], image: '🚉', strokes: 10, category: 'traffic' },
  { id: 292, char: '飞', pinyin: 'fēi', words: ['飞机', '飞行', '飞机场'], image: '✈️', strokes: 3, category: 'traffic' },
  { id: 293, char: '机', pinyin: 'jī', words: ['飞机', '机器', '手机'], image: '✈️', strokes: 6, category: 'traffic' },
  { id: 294, char: '轮', pinyin: 'lún', words: ['轮船', '车轮', '轮胎'], image: '🚢', strokes: 8, category: 'traffic' },
  { id: 295, char: '骑', pinyin: 'qí', words: ['骑车', '骑马', '骑手'], image: '🚴', strokes: 11, category: 'traffic' },
  { id: 296, char: '行', pinyin: 'xíng', words: ['行走', '行人', '自行车'], image: '🚶', strokes: 6, category: 'traffic' },
  { id: 297, char: '停', pinyin: 'tíng', words: ['停车', '停止', '停站'], image: '🅿️', strokes: 11, category: 'traffic' },
  { id: 298, char: '红', pinyin: 'hóng', words: ['红灯', '红灯停'], image: '🔴', strokes: 6, category: 'traffic' },
  { id: 299, char: '绿', pinyin: 'lǜ', words: ['绿灯', '绿灯行'], image: '🟢', strokes: 11, category: 'traffic' },
  { id: 300, char: '票', pinyin: 'piào', words: ['车票', '买票', '门票'], image: '🎫', strokes: 11, category: 'traffic' }
];

// 数字数据 - 1-100
const numbers = [
  { id: 1, number: '1', chinese: '一', pinyin: 'yī', image: '1️⃣' },
  { id: 2, number: '2', chinese: '二', pinyin: 'èr', image: '2️⃣' },
  { id: 3, number: '3', chinese: '三', pinyin: 'sān', image: '3️⃣' },
  { id: 4, number: '4', chinese: '四', pinyin: 'sì', image: '4️⃣' },
  { id: 5, number: '5', chinese: '五', pinyin: 'wǔ', image: '5️⃣' },
  { id: 6, number: '6', chinese: '六', pinyin: 'liù', image: '6️⃣' },
  { id: 7, number: '7', chinese: '七', pinyin: 'qī', image: '7️⃣' },
  { id: 8, number: '8', chinese: '八', pinyin: 'bā', image: '8️⃣' },
  { id: 9, number: '9', chinese: '九', pinyin: 'jiǔ', image: '9️⃣' },
  { id: 10, number: '10', chinese: '十', pinyin: 'shí', image: '🔟' },
  { id: 11, number: '11', chinese: '十一', pinyin: 'shí yī', image: '🔢' },
  { id: 12, number: '12', chinese: '十二', pinyin: 'shí èr', image: '🔢' },
  { id: 13, number: '13', chinese: '十三', pinyin: 'shí sān', image: '🔢' },
  { id: 14, number: '14', chinese: '十四', pinyin: 'shí sì', image: '🔢' },
  { id: 15, number: '15', chinese: '十五', pinyin: 'shí wǔ', image: '🔢' },
  { id: 16, number: '16', chinese: '十六', pinyin: 'shí liù', image: '🔢' },
  { id: 17, number: '17', chinese: '十七', pinyin: 'shí qī', image: '🔢' },
  { id: 18, number: '18', chinese: '十八', pinyin: 'shí bā', image: '🔢' },
  { id: 19, number: '19', chinese: '十九', pinyin: 'shí jiǔ', image: '🔢' },
  { id: 20, number: '20', chinese: '二十', pinyin: 'èr shí', image: '🔢' },
  { id: 21, number: '21', chinese: '二十一', pinyin: 'èr shí yī', image: '🔢' },
  { id: 22, number: '22', chinese: '二十二', pinyin: 'èr shí èr', image: '🔢' },
  { id: 23, number: '23', chinese: '二十三', pinyin: 'èr shí sān', image: '🔢' },
  { id: 24, number: '24', chinese: '二十四', pinyin: 'èr shí sì', image: '🔢' },
  { id: 25, number: '25', chinese: '二十五', pinyin: 'èr shí wǔ', image: '🔢' },
  { id: 26, number: '26', chinese: '二十六', pinyin: 'èr shí liù', image: '🔢' },
  { id: 27, number: '27', chinese: '二十七', pinyin: 'èr shí qī', image: '🔢' },
  { id: 28, number: '28', chinese: '二十八', pinyin: 'èr shí bā', image: '🔢' },
  { id: 29, number: '29', chinese: '二十九', pinyin: 'èr shí jiǔ', image: '🔢' },
  { id: 30, number: '30', chinese: '三十', pinyin: 'sān shí', image: '🔢' },
  { id: 31, number: '31', chinese: '三十一', pinyin: 'sān shí yī', image: '🔢' },
  { id: 32, number: '32', chinese: '三十二', pinyin: 'sān shí èr', image: '🔢' },
  { id: 33, number: '33', chinese: '三十三', pinyin: 'sān shí sān', image: '🔢' },
  { id: 34, number: '34', chinese: '三十四', pinyin: 'sān shí sì', image: '🔢' },
  { id: 35, number: '35', chinese: '三十五', pinyin: 'sān shí wǔ', image: '🔢' },
  { id: 36, number: '36', chinese: '三十六', pinyin: 'sān shí liù', image: '🔢' },
  { id: 37, number: '37', chinese: '三十七', pinyin: 'sān shí qī', image: '🔢' },
  { id: 38, number: '38', chinese: '三十八', pinyin: 'sān shí bā', image: '🔢' },
  { id: 39, number: '39', chinese: '三十九', pinyin: 'sān shí jiǔ', image: '🔢' },
  { id: 40, number: '40', chinese: '四十', pinyin: 'sì shí', image: '🔢' },
  { id: 41, number: '41', chinese: '四十一', pinyin: 'sì shí yī', image: '🔢' },
  { id: 42, number: '42', chinese: '四十二', pinyin: 'sì shí èr', image: '🔢' },
  { id: 43, number: '43', chinese: '四十三', pinyin: 'sì shí sān', image: '🔢' },
  { id: 44, number: '44', chinese: '四十四', pinyin: 'sì shí sì', image: '🔢' },
  { id: 45, number: '45', chinese: '四十五', pinyin: 'sì shí wǔ', image: '🔢' },
  { id: 46, number: '46', chinese: '四十六', pinyin: 'sì shí liù', image: '🔢' },
  { id: 47, number: '47', chinese: '四十七', pinyin: 'sì shí qī', image: '🔢' },
  { id: 48, number: '48', chinese: '四十八', pinyin: 'sì shí bā', image: '🔢' },
  { id: 49, number: '49', chinese: '四十九', pinyin: 'sì shí jiǔ', image: '🔢' },
  { id: 50, number: '50', chinese: '五十', pinyin: 'wǔ shí', image: '🔢' },
  { id: 51, number: '51', chinese: '五十一', pinyin: 'wǔ shí yī', image: '🔢' },
  { id: 52, number: '52', chinese: '五十二', pinyin: 'wǔ shí èr', image: '🔢' },
  { id: 53, number: '53', chinese: '五十三', pinyin: 'wǔ shí sān', image: '🔢' },
  { id: 54, number: '54', chinese: '五十四', pinyin: 'wǔ shí sì', image: '🔢' },
  { id: 55, number: '55', chinese: '五十五', pinyin: 'wǔ shí wǔ', image: '🔢' },
  { id: 56, number: '56', chinese: '五十六', pinyin: 'wǔ shí liù', image: '🔢' },
  { id: 57, number: '57', chinese: '五十七', pinyin: 'wǔ shí qī', image: '🔢' },
  { id: 58, number: '58', chinese: '五十八', pinyin: 'wǔ shí bā', image: '🔢' },
  { id: 59, number: '59', chinese: '五十九', pinyin: 'wǔ shí jiǔ', image: '🔢' },
  { id: 60, number: '60', chinese: '六十', pinyin: 'liù shí', image: '🔢' },
  { id: 61, number: '61', chinese: '六十一', pinyin: 'liù shí yī', image: '🔢' },
  { id: 62, number: '62', chinese: '六十二', pinyin: 'liù shí èr', image: '🔢' },
  { id: 63, number: '63', chinese: '六十三', pinyin: 'liù shí sān', image: '🔢' },
  { id: 64, number: '64', chinese: '六十四', pinyin: 'liù shí sì', image: '🔢' },
  { id: 65, number: '65', chinese: '六十五', pinyin: 'liù shí wǔ', image: '🔢' },
  { id: 66, number: '66', chinese: '六十六', pinyin: 'liù shí liù', image: '🔢' },
  { id: 67, number: '67', chinese: '六十七', pinyin: 'liù shí qī', image: '🔢' },
  { id: 68, number: '68', chinese: '六十八', pinyin: 'liù shí bā', image: '🔢' },
  { id: 69, number: '69', chinese: '六十九', pinyin: 'liù shí jiǔ', image: '🔢' },
  { id: 70, number: '70', chinese: '七十', pinyin: 'qī shí', image: '🔢' },
  { id: 71, number: '71', chinese: '七十一', pinyin: 'qī shí yī', image: '🔢' },
  { id: 72, number: '72', chinese: '七十二', pinyin: 'qī shí èr', image: '🔢' },
  { id: 73, number: '73', chinese: '七十三', pinyin: 'qī shí sān', image: '🔢' },
  { id: 74, number: '74', chinese: '七十四', pinyin: 'qī shí sì', image: '🔢' },
  { id: 75, number: '75', chinese: '七十五', pinyin: 'qī shí wǔ', image: '🔢' },
  { id: 76, number: '76', chinese: '七十六', pinyin: 'qī shí liù', image: '🔢' },
  { id: 77, number: '77', chinese: '七十七', pinyin: 'qī shí qī', image: '🔢' },
  { id: 78, number: '78', chinese: '七十八', pinyin: 'qī shí bā', image: '🔢' },
  { id: 79, number: '79', chinese: '七十九', pinyin: 'qī shí jiǔ', image: '🔢' },
  { id: 80, number: '80', chinese: '八十', pinyin: 'bā shí', image: '🔢' },
  { id: 81, number: '81', chinese: '八十一', pinyin: 'bā shí yī', image: '🔢' },
  { id: 82, number: '82', chinese: '八十二', pinyin: 'bā shí èr', image: '🔢' },
  { id: 83, number: '83', chinese: '八十三', pinyin: 'bā shí sān', image: '🔢' },
  { id: 84, number: '84', chinese: '八十四', pinyin: 'bā shí sì', image: '🔢' },
  { id: 85, number: '85', chinese: '八十五', pinyin: 'bā shí wǔ', image: '🔢' },
  { id: 86, number: '86', chinese: '八十六', pinyin: 'bā shí liù', image: '🔢' },
  { id: 87, number: '87', chinese: '八十七', pinyin: 'bā shí qī', image: '🔢' },
  { id: 88, number: '88', chinese: '八十八', pinyin: 'bā shí bā', image: '🔢' },
  { id: 89, number: '89', chinese: '八十九', pinyin: 'bā shí jiǔ', image: '🔢' },
  { id: 90, number: '90', chinese: '九十', pinyin: 'jiǔ shí', image: '🔢' },
  { id: 91, number: '91', chinese: '九十一', pinyin: 'jiǔ shí yī', image: '🔢' },
  { id: 92, number: '92', chinese: '九十二', pinyin: 'jiǔ shí èr', image: '🔢' },
  { id: 93, number: '93', chinese: '九十三', pinyin: 'jiǔ shí sān', image: '🔢' },
  { id: 94, number: '94', chinese: '九十四', pinyin: 'jiǔ shí sì', image: '🔢' },
  { id: 95, number: '95', chinese: '九十五', pinyin: 'jiǔ shí wǔ', image: '🔢' },
  { id: 96, number: '96', chinese: '九十六', pinyin: 'jiǔ shí liù', image: '🔢' },
  { id: 97, number: '97', chinese: '九十七', pinyin: 'jiǔ shí qī', image: '🔢' },
  { id: 98, number: '98', chinese: '九十八', pinyin: 'jiǔ shí bā', image: '🔢' },
  { id: 99, number: '99', chinese: '九十九', pinyin: 'jiǔ shí jiǔ', image: '🔢' },
  { id: 100, number: '100', chinese: '一百', pinyin: 'yī bǎi', image: '💯' }
];

// 导出数据
window.AppData = {
  characters,
  numbers,
  // 获取分类
  getCategories() {
    return {
      basic: '基础字',
      nature: '自然字',
      animal: '动物字',
      food: '食物字',
      family: '家庭字',
      action: '动作字',
      adj: '形容词',
      color: '颜色字',
      object: '物品字',
      body: '身体部位',
      school: '学校用品',
      traffic: '交通出行'
    };
  },
  // 根据分类获取汉字
  getByCategory(category) {
    return this.characters.filter(c => c.category === category);
  },
  // 获取随机汉字
  getRandomChars(count = 4) {
    const shuffled = [...this.characters].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  },
  // 获取随机数字
  getRandomNumbers(count = 4) {
    const shuffled = [...this.numbers].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
  }
};